# Existing Configuration
spring.application.name=curriculum-tracking-system
server.port=8090
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=public

# JWT Configuration
app.jwtSecret=${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
app.jwtExpirationMs=900000
app.jwtRefreshExpirationMs=604800000
api.prefix=api/v1

# Logging Configuration
logging.level.com.mozilla.curriculum_tracking_system=INFO
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Enable method security
spring.security.method.global-method-security.pre-post-enabled=true

app.admin.username=admin
app.admin.email=admin@curriculum.system
app.admin.password=Admin@123