spring:
  application:
    name: curriculum-tracking-system
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8090
  servlet:
    context-path: /

app:
  jwtSecret: ${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ}
  jwtExpirationMs: 900000  # Access token expires in 15 minutes (900000 ms)
  jwtRefreshExpirationMs: 604800000  # Refresh token expires in 7 days (604800000 ms)

api:
  prefix: api/v1